version: "3.7"

services:
  nginx:
    container_name: search_nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - "backend_network"

  php-fpm:
    container_name: search_php-fpm
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/app
    ports:
      - "9001:9001"
    depends_on:
      - mysql
    networks:
      - "backend_network"

  mysql:
    container_name: search_mysql
    image: mysql:8.1.0
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: default
      MYSQL_ROOT_PASSWORD: default
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - "backend_network"

  elasticsearch:
    container_name: search_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=default"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - "backend_network"

networks:
  backend_network:
    driver: bridge
